### ISSUE TITLE
Crash on launch 

### ISSUE THREAD

**Issue by Sunekaer** [gigaherz/ConfigurableReeds#1]
forge-28.0.45
ConfigurableCane-1.14.4-1.5.jar

log: [Crash log](https://s1.sunekaer.com/files/crash-2019-08-06_19.00.41-client.txt)

**Comment by gigaherz** [comment]
At a glance, it seems you have Random Patches in there. It seems there's some issue between randompatches and the latest version of forge, so I'm closing this as "not my fault", unless you can show that it still crashes without that coremod.
