### ISSUE TITLE
[1.14.4] Client crash when updating to Forge 1.14.4 - 28.0.45

### ISSUE THREAD

**Issue by ProsperCraft** [gigaherz/ConfigurableReeds#2]
https://gist.github.com/ProsperCraft/5ffd2ccc3e9ea591abd34b3cc4f2c969

ConfigurableCane-1.14.4-1.5

**Comment by gigaherz** [comment]
Seems to be the same crash as #1 
As I told them, I have no reason to believe it's my mod's fault. Unless you have a full log that shows some other exception earlier on, the only thing that stands out in the log is that randompatches is patching some vanilla code...

**Comment by ProsperCraft** [comment]
Hmm, can't replicate with only Configurable cane, so a bogus crash log.

**Comment by ProsperCraft** [comment]
Can't replicate with configurable cane, and random patches.

**Comment by ProsperCraft** [comment]
I will add the mods one at a time until it happens again. and then report to them.

**Comment by gigaherz** [comment]
I see, so both are collateral damage. I wonder if it's just a race condition that starts to show up with bigger packs....
One possibility that seems increasingly more probably, after both these reports and  gigaherz/ToolBelt#38
Is that some parallel event isn't properly waiting for the entire pool to join back into the main thread.

**Comment by gigaherz** [comment]
I don't know if you found the culprit yet, but someone provided a full log in the other mod's report, and it shed some light in the situation, see my reply there: https://github.com/gigaherz/ToolBelt/issues/38#issuecomment-519652991
