### ISSUE TITLE
same issue as ??? 

### ISSUE THREAD

**Issue by Josetheyoutuber** [gigaherz/ConfigurableReeds#5]
the config button doesnt let me press it and im using minecraft 1.15.2 am i doing something wrong?

**Comment by gigaherz** [comment]
Forge still doesn't implement a config GUI for mods to use. Any mod you see with a working config button has implemented the GUI themselves, which I'm not interested in doing.
You can edit the config by opening the save folder, going to the "serverconfigs" folder inside it, and opening the configurablecane-server.toml file in your favorite text editor. If you are making a modpack, you can then copy that file over to the defaultconfigs folder outside the save, and it will get applied when creating new saves.

**Comment by Josetheyoutuber** [comment]
Thanks for the help
