### ISSUE TITLE
Latest 1.16.5 Version doesn't create a config file

### ISSUE THREAD

**Issue by Chancho91** [gigaherz/ConfigurableReeds#9]
Please fix

**Comment by gigaherz** [comment]
Hmm weird, the file should appear in the save folder, under serverconfigs. You can also use [Configured](https://www.curseforge.com/minecraft/mc-mods/configured) to get an ingame config menu.

**Comment by Chancho91** [comment]
Didn't know the file is in my save folder, thanks
